# Note:
# Consider overriding all the following variables at Ansible runtime via --extra-vars
# - keyfile_content
# - mongo_root_password
# - pmm_server_pwd
# - mongodb_pmm_user_pwd
# - pbmpwd
# - access_key_id (used for accesing S3 bucket for Backups)
# - secret_access_key (used for accesing S3 bucket for Backups)
# - encryption_key_content (if using encryption at rest)
# - vault_tokenfile_content (if using Hashicorp Vault)

#########################
## General configuration
#########################

ansible_python_interpreter: /usr/bin/python3

# MongoDB version as per "percona-release". Availability of MongoDB version depend on the OS version.
# e.g. -> Available repositories for centos7: psmdb-36 psmdb-40 psmdb-42 psmdb-44 psmdb-50 psmdb-60
#mongo_release: psmdb-70
mongo_release: psmdb-80

# We can also use perconalab/pmm-server-fb:PR-number-hash or perconalab/pmm-server:dev-latest. In that case set experimental to true.
#pmm_image: perconalab/pmm-server:3-dev-latest
pmm_image: docker.io/percona/pmm-server:latest
#pmm_image: docker.io/percona/pmm-server:3

#pmm_client_repo: pmm2-client experimental
#pmm_client_repo: pmm2-client
pmm_client_repo: pmm3-client

#########################
## Package sources
#########################

# you can use a specific version instead of the default `latest` by passing the package names and version e.g. "percona-server-mongodb-7.0.12-7.el9"
mongod_packages:
  - percona-server-mongodb
  - percona-mongodb-mongosh

mongos_packages:
   - percona-server-mongodb-mongos
   - percona-mongodb-mongosh   

pbm_package:
  - percona-backup-mongodb

pmm_client_package:
  - pmm-client

disable_telemetry: false

##########
# MongoDB 
##########

mongo_admin_user: root
# Warning! This is just an example, replace with your own for prod use!
mongo_admin_password: percona

mongod_log_path: /var/log/mongo/
mongod_path: /var/lib/mongo/

thp_location: /usr/lib/systemd/system/disable-thp.service

########################
## Member Authentication
########################

# use_tls: true/false. Controls if Mongo uses keyfile or x509 certificates for member authentication. Also controls if clients need to use TLS to connect.
use_tls: false

# keyFile is only relevant if use_tls: false. Run `openssl rand -base64 741` to generate a new key
keyFile_location: /etc/mongod_keyfile

# Warning! This is just an example, replace with your own for prod use!
keyfile_content: |
  8pYcxvCqoe89kcp33KuTtKVf5MoHGEFjTnudrq5BosvWRoIxLowmdjrmUpVfAivh
  CHjqM6w0zVBytAxH1lW+7teMYe6eDn2S/O/1YlRRiW57bWU3zjliW3VdguJar5i9

# The next 2 options are only relevant if use_tls: true
certificateKeyFile: /etc/ssl/server.pem
CAFile: /etc/ssl/test-ca.pem

##########################
## Data-at-rest Encryption
##########################

# keyfile_encryption: true/false
keyfile_encryption: false
# Warning! This is just an example, replace with your own for prod use!
encryption_key_content: |
  vvMTZ3dnSbG7wc6DkPpt+rp3Cc+jF8lJsYlq6QE1yEM=
# path to the keyfile to encrypt
encryption_keyfile: /opt/mongodb.key

# vault_encryption: true/false - set to true to use Hashicorp Vault instead of local keyfile
vault_encryption: false
vault_server: vault.example.com
vault_port: 8200
# path to the token used by MongoDB to access Vault
vault_tokenfile: /etc/mongodb/token
vault_cafile: /etc/mongodb/vault.crt
# path to the secret within Vault
vault_secret: secret/data/dc/psmongodb1

##############
# Vault Server
##############

vault_config_path: /etc/vault.d/vault.hcl
root_token: |
  s.uTrHtzsZnEE7KyHeA797CkWA
mongodb_policy_name: "mongodb-policy"
mongodb_policy_hcl: |
  path "secret/data/dc/*" {
    capabilities = ["create", "read", "update", "delete", "list"]
  }
  path "secret/metadata/*" {
    capabilities = ["read"]
  }
  path "secret/config" {
    capabilities = ["read"]
  }
mongodb_token_ttl: "30d"

##################
## Monitoring
##################

# For PMM 3 pmm_port is 8443. For PMM 2 it is 443
#pmm_port: 443
pmm_port: 8443
pmm_external_port: 8443

# PMM server parameters
pmm_dir: /var/lib/docker
pmm_server_user: admin
# Warning! This is just an example, replace with your own for prod use!
pmm_server_pwd: admin

# PMM agent parameters
mongodb_pmm_user: pmm
# Warning! This is just an example, replace with your own for prod use!
mongodb_pmm_user_pwd: percona

# Warning! This is just an example, replace with your own for prod use!
watchtower_token: 89220f28d5017b6a5806a7c589485c2b

#env_tag: test

# The pmm-admin --cluster argument is only applicable for sharded clusters.
# The cluster name is automatically put into the inventory file generated by Terraform.
# If not provisioning servers with Terraform uncomment the following line and provide the desired cluster name here:
#
#cluster: dev

###############
## Backup
###############
  
# PBM database user and password
pbmuser: pbm
# Warning! This is just an example, replace with your own for prod use!
pbmpwd: secretpwd
# also can be logical
pbm_backup_type: physical
# how long to keep backups
pbm_retention_days: 3
# use for the cron job with backup time
pbm_backup_hour: 0
pbm_backup_minute: 2
pbm_purge_hour: 0
pbm_purge_minute: 2
# older pbm versions used a dedicated pbm user
pbm_os_user: mongod

pbm_config_path: /etc/pbm-storage.conf

# backup location - use 'filesystem' for locally mounted NFS drive. For cloud storage use gcs, azure or s3
#storage_provider: filesystem

# only relevant if for storage_provider: filesystem
pbm_path: /backup

# Below options are only relevant if you are using storage_provider != filesystem
#
# A custom prefix for the directory structure created by pbm inside the storage bucket. By default the cluster name is used.
#prefix: pbm
#
# The region, bucket, endpoint and keys are put into the inventory file by Terraform. If not provisioning servers with Terraform uncomment the following lines and modify as needed:
#
#region: northamerica-northeast1
#bucket: dev-mongo-backups
#endpointUrl: https://storage.googleapis.com
#
# the access and secret access keys are best provided via --extra-vars at runtime to avoid exposing them in the inventory file
#access_key_id: *****
#secret_access_key: *****