---
- import_playbook: os_conf.yml

- import_playbook: percona_release.yml

- import_playbook: mongod_install.yml

- import_playbook: mongos_install.yml

- import_playbook: sharding_setup.yml

- import_playbook: pbm_install.yml

- import_playbook: pmm_server_install.yml

- import_playbook: pmm_client_install.yml