---
- name: Install mongos routers
  hosts: mongos
  become: yes
  tags: mongos
  environment:
    PERCONA_TELEMETRY_DISABLE: "{{ '1' if disable_telemetry else '0' }}"
  tasks:
    - name: Copy RPM files from local machine
      block:
        - name: Copy files
          copy:
            src: "{{ local_rpm_location }}"
            dest: "{{ target_rpm_location }}"

        - name: Find copied RPMs
          find:
            paths: "{{ target_rpm_location }}"
            patterns: "*.rpm"
          register: percona_rpms

        - name: Get the paths of copied files
          set_fact:
            rpm_list: "{{ percona_rpms.files | map(attribute='path') | list }}"

        - name: Install copied RPM files
          yum:
            name: "{{ rpm_list }}"
            state: present
            disablerepo: "*"

      when: copy_files | bool

    - name: Install mongod files from repository
      block:
        - name: Enable specific MongoDB version
          shell: "/usr/bin/percona-release enable {{ mongo_release }}"

        - name: Install mongos RPM from repository
          package:
            name: "{{ item }}"
            state: present
          with_items: "{{ mongos_packages }}"

      when: not copy_files | bool

    - name: Create logs directory
      file:
        path: "{{ mongod_log_path }}"
        state: directory
        mode: '0755'
        owner: mongod
        group: mongod

    - name: Set up an alias to login easily to mongos
      become: yes
      lineinfile:
        dest: /etc/profile
        line: alias mongo='mongosh admin {% if use_tls %}--tls --tlsCertificateKeyFile {{ certificateKeyFile }} --tlsCAFile {{ certificateKeyFile }} --tlsAllowInvalidCertificates{% endif %} -u {{ mongo_admin_user }} -p {{ mongo_admin_password }} --port {{ mongo_port }} --host {{ ansible_fqdn }}'
        state: present

    - name: Set up shared mongo keyfile 
      become: yes
      copy:
        dest: "{{ keyFile_location }}"
        content: "{{ keyfile_content }}"
        owner: mongod
        group: root
        mode: 0600
      when: not use_tls | bool

    - name: Copy mongos.conf
      template:
        src: templates/mongos.conf.j2
        dest: /etc/mongos.conf
        owner: root
        group: root
        mode: 0644

    - name: Setup logrotate conf for mongos
      template:
        src: templates/logrotate-mongos.conf.j2
        dest: /etc/logrotate.d/mongos
        mode: 0644

    - name: Copy systemd template file for mongos
      template:
        src: templates/mongos.service.j2
        dest: /usr/lib/systemd/system/mongos.service
        mode: 0644

    - name: Disable SELinux
      shell: /usr/sbin/setenforce 0

    - name: Disable Percona telemetry
      systemd:
        name: percona-telemetry-agent
        enabled: false
        state: stopped
        daemon_reload: yes
      ignore_errors: true
      when: disable_telemetry | bool

    - name: Start the mongos router service
      systemd:
        name: mongos
        state: started
        enabled: yes
        daemon_reload: yes
