---
#- name: Gather facts from the config servers
#  hosts: cfg
#  gather_facts: yes
#  tags: mongos
#  tasks:
#    - name: Dummy task to force fact gathering
#      debug:
#        msg: "Facts collected for cfg servers"

- name: Install mongos routers
  hosts: mongos
  become: yes
  tags: mongos

  environment:
    PERCONA_TELEMETRY_DISABLE: "{{ '1' if disable_telemetry else '0' }}"

  vars:
    mongo_tls_flags: >-
      {% if use_tls %}
      --tls
      --tlsCertificateKeyFile {{ certificateKeyFile }}
      --tlsCAFile {{ CAFile }}
      --tlsAllowInvalidCertificates
      {% endif %}

  tasks:    
    - name: Enable specific MongoDB version
      shell: "/usr/bin/percona-release enable {{ mongo_release }}"

    - name: Install mongos packages from repository
      package:
        name: "{{ mongos_packages }}"
        state: present

    - name: Disable Percona telemetry
      systemd:
        name: percona-telemetry-agent
        enabled: false
        state: stopped
        daemon_reload: yes
      ignore_errors: true
      when: disable_telemetry | bool

    - name: Create logs directory for mongos 
      file:
        path: "{{ mongod_log_path }}"
        state: directory
        mode: '0755'
        owner: mongod
        group: mongod

    - name: Ensure audit log directory exists
      file:
        path: "{{ audit_log_path | dirname }}"
        state: directory
        mode: '0750'
        owner: mongod
        group: mongod
      when: enable_audit | bool

    - name: Configure mongo shell alias
      lineinfile:
        path: /etc/profile
        line: >
          alias mongo='mongosh admin {{ mongo_tls_flags }}
          -u {{ mongo_admin_user }}
          -p {{ mongo_admin_password }}
          --port {{ mongo_port }}
          --host {{ ansible_facts['fqdn'] }}'
        state: present

    - name: Set up shared mongo keyfile 
      become: yes
      copy:
        dest: "{{ keyFile_location }}"
        content: "{{ keyfile_content }}"
        owner: mongod
        group: root
        mode: 0600
      when: not use_tls | bool

    - name: Copy mongos.conf
      template:
        src: templates/mongos.conf.j2
        dest: /etc/mongos.conf
        owner: root
        group: root
        mode: 0644

    - name: Setup logrotate conf for mongos
      template:
        src: templates/logrotate-mongos.conf.j2
        dest: /etc/logrotate.d/mongos
        mode: 0644

    - name: Copy systemd template file for mongos
      template:
        src: templates/mongos.service.j2
        dest: /usr/lib/systemd/system/mongos.service
        mode: 0644

    - name: Set SELinux to disabled until reboot
      command: /usr/sbin/setenforce 0
      when: ansible_selinux.status == "enabled"
      ignore_errors: yes

    - name: Disable SELinux permanently
      lineinfile:
        path: ansible_facts['selinux']['config_file']
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
      when: ansible_facts['selinux'] is defined and ansible_facts['selinux']['config_file'] is defined

    - name: Start the mongos router service
      systemd:
        name: mongos
        state: restarted
        enabled: yes
        daemon_reload: yes
