---
- name: Prepare OS configuration
  hosts: cfg:shards:replsets
  tags: os_conf
  become : yes
  strategy: free

  vars:

    mongo_sysctl:
      vm.swappiness: 1
      vm.dirty_ratio: 15
      vm.dirty_background_ratio: 5
      net.core.somaxconn: 65535
      vm.max_map_count: 102400

    mongo_major: "{{ mongo_release | regex_search('[0-9]+$') | int }}"

    pam_limits:
      - domain: "*"
        type: soft
        item: nofile
        value: 64000
      - domain: "*"
        type: hard
        item: nofile
        value: 64000

  tasks:

    - name: Tune sysctl values
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: false
      loop: "{{ mongo_sysctl | dict2items }}"
      notify: reload sysctl

    - name: Configure PAM limits
      community.general.pam_limits:
        domain: "{{ item.domain }}"
        limit_type: "{{ item.type }}"
        limit_item: "{{ item.item }}"
        value: "{{ item.value }}"
      loop: "{{ pam_limits }}"

    - name: Add PAM limits to login
      community.general.pamd:
        state: after
        type: session
        module_path: postlogin
        control: include
        new_type: session
        new_module_path: pam_limits.so
        new_control: required
        name: login

    - name: Deploy disable THP systemd service (Mongo < 8)
      template:
        src: disable-thp.service.j2
        dest: "{{ thp_location }}"
        owner: root
        group: root
        mode: "0644"
      when:
        - mongo_major | int < 80
      notify:
        - reload systemd
        - start disable thp

  handlers:

    - name: reload sysctl
      command: sysctl --system

    - name: reload systemd
      command: systemctl daemon-reload

    - name: start disable thp
      systemd:
        name: disable-thp
        enabled: true
        state: started