---
- name: Prepare nodes
  tags: os_conf
  hosts: cfg:shards:replsets:mongos
  become: yes
  environment:
    PERCONA_TELEMETRY_DISABLE: "{{ '1' if disable_telemetry else '0' }}"
  tasks:
    - name: Load OS-specific variables
      include_vars: "vars/{{ ansible_facts['os_family'] }}.yml"

    - name: Install percona release for Ubuntu
      block:

        - name: Install dependencies for percona-release
          ansible.builtin.apt:
            name:
              - curl
              - gnupg2
              - lsb-release 
            state: present
            update_cache: yes

        - name: Download percona-release package
          ansible.builtin.get_url:
            url: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
            dest: /tmp/percona-release_latest.deb
            mode: "666"

        - name: Install percona-release package
          ansible.builtin.apt:
            deb: /tmp/percona-release_latest.deb
            state: present

        - name: Update apt package cache
          ansible.builtin.apt:
            update_cache: yes

      when: ansible_facts['os_family'] == 'Debian'

    - name: Install percona release for RedHat
      block:
        
        - name: Install Percona GPG key
          rpm_key:
            key: "{{ percona_key_location }}"
            state: present

        - name: Install percona-release package 
          package:
            name: "{{ percona_release_package }}"
            state: present    

      when: ansible_facts['os_family'] == 'RedHat'
