---
- name: install PMM client
  hosts: cfg:shards:replsets:mongos
  become: yes
  tags: install
  environment:
    PERCONA_TELEMETRY_DISABLE: "{{ '1' if disable_telemetry else '0' }}"
  tasks:
    - name: install RPM files from repository
      block:
        - name: Enable PMM client repository
          shell: "/usr/bin/percona-release enable {{ pmm_client_repo }}"

        - name: install pmm-client RPM from repository
          package:
            name: "{{ item }}"
            state: present
          with_items: "{{ pmm_client_package }}"

      when: not copy_files | bool

    - name: disable Percona telemetry
      systemd:
        name: percona-telemetry-agent
        enabled: false
        state: stopped
        daemon_reload: yes
      ignore_errors: true
      when: disable_telemetry | bool

- name: configure monitoring with PMM
  hosts: cfg:shards:replsets:mongos
  become: true
  tags: monitoring
  tasks:
    - name: ensure pmm-agent is started
      service:
        name: pmm-agent
        state: started

    - name: point pmm-agent to the PMM server
      shell: pmm-admin config --server-url=https://{{ pmm_server_user }}:{{ pmm_server_pwd }}@{{ hostvars[groups['pmm'][0]].inventory_hostname }}:{{ pmm_external_port }} --server-insecure-tls --force

    - name: Add MongoDB metrics collector
      shell: >
        pmm-admin add mongodb
        --environment={{ env_tag }}
        {% if cluster is defined %}
        --cluster {{ cluster }}
        {% endif %}
        --host={{ ansible_fqdn }}
        --port={{ mongo_port }}
        --tls-skip-verify
        {% if arbiter is not defined %}
        --username={{ mongodb_pmm_user }} --password={{ mongodb_pmm_user_pwd }}
        {% if use_tls | bool %}
        --tls --tls-certificate-key-file={{ certificateKeyFile }} --tls-ca-file={{ CAFile }}
        {% endif %}
        --enable-all-collectors
        {% endif %}