---
- hosts: mongos:cfg:shards:replsets
  gather_facts: false
  become: yes
  tasks:
    - name: Remove server from PMM
      shell: pmm-admin unregister --force
      ignore_errors: yes

    - name: Stop pmm client
      systemd:
        name: pmm-agent
        state: stopped
      ignore_errors: yes

    - name: Remove certificate related files    
      shell: rm -f /etc/ssl/*.pem    

- hosts: mongos
  gather_facts: false
  become: yes
  tasks:
    - name: Stop mongos service
      systemd:
        name: mongos
        state: stopped
      ignore_errors: yes

- hosts: cfg:shards:replsets
  gather_facts: false
  become: yes
  tasks:
    - name: Stop mongod service
      systemd:
        name: "{{ item }}"
        state: stopped
      with_items:
        - mongod
        - pbm-agent
      ignore_errors: yes

    - name: Remove datadir contents
      shell: rm -rf {{ mongod_path }}/*

- hosts: pmm
  gather_facts: false
  become: yes
  tasks:
    - name: Remove PMM server
      shell: docker rm pmm-server watchtower renderer --force
      ignore_errors: yes

    - name: Remove PMM volume
      shell: docker volume rm pmm-data --force
      ignore_errors: yes            

    - name: Remove PMM network
      shell: docker network rm pmm-network --force
      ignore_errors: yes   

    - name: Remove certificate related files    
      shell: rm -f /etc/ssl/*.{crt,csr,pem,key,cnf,srl}