---
- hosts: mongos:cfg:shard*:rs*
  gather_facts: false
  become: yes
  tasks:
    - name: remove server from PMM
      shell: pmm-admin unregister --force
      ignore_errors: yes

    - name: stop pmm client
      systemd:
        name: pmm-agent
        state: stopped
      ignore_errors: yes

    - name: remove certificate related files    
      shell: rm -f /etc/ssl/*.pem    

- hosts: mongos
  gather_facts: false
  become: yes
  tasks:
    - name: stop mongos service
      systemd:
        name: mongos
        state: stopped
      ignore_errors: yes

- hosts: cfg:shard*:rs*
  gather_facts: false
  become: yes
  tasks:
    - name: stop mongod service
      systemd:
        name: "{{ item }}"
        state: stopped
      with_items:
        - mongod
        - pbm-agent
      ignore_errors: yes

    - name: remove datadir contents
      shell: rm -rf {{ mongod_path }}/*

- hosts: pmm
  gather_facts: false
  become: yes
  tasks:
    - name: stop PMM server
      shell: docker stop pmm-server
      ignore_errors: yes

    - name: remove PMM server and data
      shell: docker rm pmm-server pmm-data
      ignore_errors: yes

    - name: remove certificate related files    
      shell: rm -f /etc/ssl/*.{crt,csr,pem,key,cnf,srl}