---
- hosts: mongos
  become: yes
  gather_facts: false
  tasks:
    - name: stop mongos service
      systemd:
        name: mongos
        state: stopped
      ignore_errors: yes

- hosts: mongos:cfg:shard*:rs*
  tasks:
     - name: remove server from pmm
       shell: pmm-admin --server-url=https://{{ pmm_server_user }}:{{ pmm_server_pwd }}@{{ pmm_private_ip }}:443 --server-insecure-tls remove mongodb {{ inventory_hostname }}.c.{{project_id}}.internal-mongodb
       ignore_errors: yes

- hosts: cfg:shard*:rs*
  gather_facts: false
  tags: mongod
  become: yes
  tasks:
     - name: stop mongod service
       systemd:
         name: "{{ item }}"
         state: stopped
       with_items:
         - mongod
         - pbm-agent

     - name: remove datadir contents
       shell: rm -rf {{ mongod_path }}/*

- hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: stop pmm client
      systemd:
        name: pmm-agent
        state: stopped
