---
- hosts: cfg:shards:replsets
  gather_facts: false
  become: yes
  tasks:
    - name: Wipe arbiter directory contents
      shell: rm -rf {{ mongod_path }}/*
      when: arbiter is defined

    - name: Restart mongod service
      systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - mongod

    - name: Restart pbm service
      systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - pbm-agent
      when: arbiter is not defined

    - name: Figure out the Mongo TLS options
      set_fact:
        mongo_uri_tls: "/?tls=true&tlsCertificateKeyFile={{ certificateKeyFile }}&tlsCAFile={{ CAFile }}"
      when: use_tls | bool

- hosts: mongos
  become: yes
  gather_facts: false
  tasks:
    - name: Restart mongos service
      systemd:
        name: mongos
        state: restarted

- name: Resync pbm storage (replsets)
  hosts: replsets
  become: true
  vars:
    replset_group: "{{ (group_names | difference(['replsets', 'shards']))[0] }}"
    replset_name: "{{ replset_group if cluster is defined and cluster == replset_group else (cluster ~ '-' ~ replset_group if cluster is defined else replset_group) }}"

  tasks:
    - block:
        - name: generate PBM_MONGODB_URI
          set_fact:
            mongodb_uri: "mongodb://{{ pbmuser }}:{{ pbmpwd }}@{% for h in groups[replset_group] %}{{ h }}:{{ mongo_port }}{% if not loop.last %},{% endif %}{% endfor %}/?replicaSet={{ replset_name }}&authSource=admin{% if use_tls %}&tls=true&tlsCertificateKeyFile={{ certificateKeyFile }}&tlsCAFile={{ CAFile }}{% endif %}"

        - name: Resync pbm storage
          shell: pbm config --force-resync --mongodb-uri '{{ mongodb_uri }}'

      when: inventory_hostname == groups[replset_group][0]     

- name: Resync pbm storage (sharded clusters)
  hosts: cfg
  become: true
  tasks:
    - block:
        - name: generate PBM_MONGODB_URI
          set_fact:
            mongodb_uri: "mongodb://{{ pbmuser }}:{{ pbmpwd }}@{% for h in groups['cfg'] %}{{ h }}:{{ cfg_server_port }}{% if not loop.last %},{% endif %}{% endfor %}/?replicaSet={{ cluster }}-cfg&authSource=admin{% if use_tls %}&tls=true&tlsCertificateKeyFile={{ certificateKeyFile }}&tlsCAFile={{ CAFile }}{% endif %}"

        - name: Resync pbm storage
          shell: pbm config --force-resync --mongodb-uri '{{ mongodb_uri }}'

      when: inventory_hostname == groups['cfg'][0]     

- hosts: cfg:shards:replsets:mongos
  become: yes
  gather_facts: false
  tasks:
    - name: Restart pmm service
      systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - pmm-agent
